apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskdeployment
  labels:
    app: task1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: taskjenkins
        image: vasanthapoorani/task1_jenkins:latest
        ports:
        - containerPort: 80
        
---
  
apiVersion: v1
kind: Service
metadata:
  name: taskservice
spec:
  selector:
    app: task1
  ports:
    - port: 8765
      nodePort: 30163
      targetPort: 9376
  type: LoadBalancer
